name: CI

on:
  push:
    paths:
      - 'src/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'rustfmt.toml'
      - 'config/**'
      - '.github/workflows/**'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  ci:
    name: ${{ matrix.toolchain }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Add clippy
        run: rustup component add clippy
      - name: Add rustfmt
        run: rustup component add rustfmt
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo clippy --verbose
      - run: cargo fmt -- --check
